/* Sections complémentaires de la fiche projet. Injecté dans l'IIFE principal. */
var projectDetailsUI={initialized:false,opener:null,collapsed:{}};

function pmDetailId(){return typeof uid==="function"?uid():"detail-"+Date.now().toString(36)+Math.random().toString(36).slice(2,8);}
function pmDetailItems(p,key){return Array.isArray(p&&p[key])?p[key]:[];}
function pmDetailUrl(value){
  try{var u=new URL(String(value||"").trim());return (u.protocol==="http:"||u.protocol==="https:")?u.href:"";}catch(e){return "";}
}
function pmDetailDateTime(value){
  if(!value)return "Date inconnue";var d=new Date(value);return isNaN(d)?String(value):d.toLocaleString("fr-FR",{dateStyle:"medium",timeStyle:"short"});
}
function pmDetailHistoryType(value){return {decision:"Décision",task:"Action",project:"Projet",collection:"Suivi"}[value]||"Événement";}
function pmDetailEmpty(text){return '<div class="pmDetailEmpty">'+pmE(text)+'</div>';}
function pmDetailSection(key,title,summary,body,addLabel,pid){
  var pref=projectDetailsUI.collapsed[pid+":"+key],open=pref!==true&&(key!=="history"||pref===false);
  return '<details class="pmCard pmDetailSection" data-detail-section="'+pmE(key)+'" data-pid="'+pmE(pid)+'"'+(open?' open':'')+'><summary><span><strong>'+pmE(title)+'</strong><small>'+pmE(summary)+'</small></span></summary><div class="pmDetailSectionBody">'+body+(addLabel?'<button type="button" class="pmBtn pmDetailAdd" data-detail-action="add" data-kind="'+pmE(key)+'" data-pid="'+pmE(pid)+'">+ '+pmE(addLabel)+'</button>':'')+'</div></details>';
}

function pmProjectDetailsHtml(p){
  if(!p)return "";var pid=p.id;
  var milestones=pmDetailItems(p,"milestones"),pending=milestones.filter(function(x){return !x.done;}).length;
  var milestoneBody=milestones.length?'<div class="pmDetailList">'+milestones.map(function(x){return '<div class="pmDetailRow"><label class="pmDetailCheck"><input type="checkbox" data-detail-action="toggle" data-kind="milestones" data-pid="'+pmE(pid)+'" data-id="'+pmE(x.id)+'"'+(x.done?' checked':'')+'><span><b>'+pmE(x.title)+'</b><small>'+(x.date?pmE(pmDate(x.date)):"Sans date")+'</small></span></label><button class="pmBtn pmBtnIcon" data-detail-action="edit" data-kind="milestones" data-pid="'+pmE(pid)+'" data-id="'+pmE(x.id)+'" aria-label="Modifier le jalon">✎</button></div>';}).join("")+'</div>':pmDetailEmpty("Aucun jalon. Ajoutez les dates qui structurent le projet.");
  var readiness=pmDetailItems(p,"readiness"),ready=readiness.filter(function(x){return x.done;}).length;
  var readinessBody=readiness.length?'<div class="pmDetailList">'+readiness.map(function(x){return '<div class="pmDetailRow"><label class="pmDetailCheck"><input type="checkbox" data-detail-action="toggle" data-kind="readiness" data-pid="'+pmE(pid)+'" data-id="'+pmE(x.id)+'"'+(x.done?' checked':'')+'><span><b>'+pmE(x.title)+'</b></span></label><button class="pmBtn pmBtnIcon" data-detail-action="edit" data-kind="readiness" data-pid="'+pmE(pid)+'" data-id="'+pmE(x.id)+'" aria-label="Modifier l’élément">✎</button></div>';}).join("")+'</div>':pmDetailEmpty("Aucun point de préparation à vérifier.");
  var documents=pmDetailItems(p,"documents");
  var documentBody=documents.length?'<div class="pmDetailList">'+documents.map(function(x){var url=x.kind==="url"?pmDetailUrl(x.target):"";return '<div class="pmDetailRow pmDocumentRow"><span class="pmDetailRowMain"><b>'+pmE(x.title)+'</b><small>'+pmE(x.target||"Emplacement non renseigné")+'</small></span><span class="pmDocumentActions">'+(x.kind==="url"?(url?'<a class="pmBtn" href="'+pmE(url)+'" target="_blank" rel="noopener noreferrer">Ouvrir</a>':'<span class="pmDetailInvalid">Lien invalide</span>'):'<button class="pmBtn" data-detail-action="copy-path" data-target="'+pmE(x.target||"")+'">Copier le chemin</button>')+'<button class="pmBtn pmBtnIcon" data-detail-action="edit" data-kind="documents" data-pid="'+pmE(pid)+'" data-id="'+pmE(x.id)+'" aria-label="Modifier le document">✎</button></span></div>';}).join("")+'</div>':pmDetailEmpty("Aucun document référencé. Ajoutez un lien OneDrive ou un chemin sur ce PC.");
  var contacts=pmDetailItems(p,"contacts");
  var contactBody=contacts.length?'<div class="pmDetailList">'+contacts.map(function(x){return '<div class="pmDetailRow"><span class="pmDetailRowMain"><b>'+pmE(x.name)+'</b><small>'+pmE(x.role||"Responsabilité non renseignée")+'</small><small>'+pmE([x.email,x.phone].filter(Boolean).join(" · ")||"Coordonnées non renseignées")+'</small></span><button class="pmBtn pmBtnIcon" data-detail-action="edit" data-kind="contacts" data-pid="'+pmE(pid)+'" data-id="'+pmE(x.id)+'" aria-label="Modifier le contact">✎</button></div>';}).join("")+'</div>':pmDetailEmpty("Aucun contact. Ajoutez les personnes et leurs responsabilités.");
  var history=pmDetailItems(p,"history").slice().sort(function(a,b){return String(b.at||"").localeCompare(String(a.at||""));});
  var historyBody='<form class="pmDecisionForm" data-detail-form="decision"><input type="hidden" name="pid" value="'+pmE(pid)+'"><label for="pmDecisionText" class="sr">Nouvelle décision</label><textarea id="pmDecisionText" name="text" maxlength="1000" required placeholder="Consigner une décision et son contexte…"></textarea><button class="pmBtn pmBtnPrimary" type="submit">Ajouter la décision</button><div class="pmFormError" role="alert"></div></form>'+(history.length?'<ol class="pmDetailHistory">'+history.map(function(x){return '<li><time datetime="'+pmE(x.at||"")+'">'+pmE(pmDetailDateTime(x.at))+'</time><div><b>'+pmE(pmDetailHistoryType(x.type))+'</b><p>'+pmE(x.text||"")+'</p></div></li>';}).join("")+'</ol>':pmDetailEmpty("Aucun événement enregistré."));
  return '<section class="pmDetails" aria-label="Informations complémentaires du projet"><div class="pmDetailsGrid">'
    +pmDetailSection("milestones","Jalons",milestones.length?(pending?pending+" à venir":"Tous terminés"):"Aucun jalon",milestoneBody,"Ajouter un jalon",pid)
    +pmDetailSection("readiness","Prêt à démarrer",readiness.length?(ready===readiness.length?"Prêt":(readiness.length-ready)+" élément"+(readiness.length-ready>1?"s":"")+" à vérifier"):"Aucun élément",readinessBody,"Ajouter un élément",pid)
    +pmDetailSection("documents","Documents",documents.length+" référence"+(documents.length>1?"s":""),documentBody,"Ajouter un document",pid)
    +pmDetailSection("contacts","Contacts et responsabilités",contacts.length+" contact"+(contacts.length>1?"s":""),contactBody,"Ajouter un contact",pid)
    +pmDetailSection("history","Décisions et historique",history.length+" événement"+(history.length>1?"s":""),historyBody,"",pid)
    +'</div></section>';
}

function pmDetailFields(kind,item){
  item=item||{};if(kind==="milestones")return '<div class="pmField pmFieldFull"><label for="pmDetailTitle">Titre *</label><input id="pmDetailTitle" name="title" maxlength="160" required value="'+pmE(item.title||"")+'" autofocus></div><div class="pmField pmFieldFull"><label for="pmDetailDate">Date</label><input id="pmDetailDate" type="date" name="date" value="'+pmE(item.date||"")+'"></div>';
  if(kind==="readiness")return '<div class="pmField pmFieldFull"><label for="pmDetailTitle">Élément à vérifier *</label><input id="pmDetailTitle" name="title" maxlength="200" required value="'+pmE(item.title||"")+'" autofocus></div>';
  if(kind==="documents")return '<div class="pmField pmFieldFull"><label for="pmDetailTitle">Nom *</label><input id="pmDetailTitle" name="title" maxlength="160" required value="'+pmE(item.title||"")+'" autofocus></div><div class="pmField"><label for="pmDetailKind">Type *</label><select id="pmDetailKind" name="kind"><option value="url"'+(item.kind!=="local"?' selected':'')+'>Lien OneDrive ou web</option><option value="local"'+(item.kind==="local"?' selected':'')+'>Chemin sur ce PC</option></select></div><div class="pmField"><label for="pmDetailTarget">Adresse ou chemin *</label><input id="pmDetailTarget" name="target" maxlength="2000" required value="'+pmE(item.target||"")+'" placeholder="https://… ou C:\\…"></div>';
  return '<div class="pmField"><label for="pmDetailName">Nom *</label><input id="pmDetailName" name="name" maxlength="160" required value="'+pmE(item.name||"")+'" autofocus></div><div class="pmField"><label for="pmDetailRole">Responsabilité</label><input id="pmDetailRole" name="role" maxlength="200" value="'+pmE(item.role||"")+'"></div><div class="pmField"><label for="pmDetailEmail">E-mail</label><input id="pmDetailEmail" type="email" name="email" maxlength="254" value="'+pmE(item.email||"")+'"></div><div class="pmField"><label for="pmDetailPhone">Téléphone</label><input id="pmDetailPhone" type="tel" name="phone" maxlength="80" value="'+pmE(item.phone||"")+'"></div>';
}
function pmDetailOpen(kind,pid,id,opener){
  var p=PM.get(pid),items=pmDetailItems(p,kind),item=items.find(function(x){return x.id===id;}),form=document.getElementById("pmDetailForm");if(!p||!form)return;
  form.reset();form.elements.pid.value=pid;form.elements.collection.value=kind;form.elements.itemId.value=id||"";form.querySelector(".pmDetailDynamicFields").innerHTML=pmDetailFields(kind,item);form.querySelector(".pmFormError").textContent="";form.querySelector('[data-detail-action="delete"]').hidden=!item;
  document.getElementById("pmDetailDialogTitle").textContent=(item?"Modifier ":"Ajouter ")+({milestones:"un jalon",readiness:"un élément",documents:"un document",contacts:"un contact"}[kind]||"un élément");projectDetailsUI.opener=opener;pmOpenDialog("pmDetailDialog",opener);
}
function pmDetailRender(){if(typeof renderProjectsUI==="function")renderProjectsUI();}
function pmDetailUpdate(pid,kind,items,message){try{PM.update(pid,(function(){var o={};o[kind]=items;return o;})());pmDetailRender();if(message)pmNotify(message);return true;}catch(e){pmNotify(e.message||"Modification impossible.");return false;}}
function pmDetailCopy(value,button){
  function fallback(){var ta=document.createElement("textarea");ta.value=value;ta.readOnly=true;ta.style.position="fixed";ta.style.opacity="0";document.body.appendChild(ta);ta.select();var ok=false;try{ok=document.execCommand("copy");}catch(e){}ta.remove();if(!ok){var range=document.createRange(),sel=window.getSelection();button.insertAdjacentHTML("afterend",'<input class="pmCopyFallback" aria-label="Chemin à copier" value="'+pmE(value)+'">');var input=button.nextElementSibling;range.selectNodeContents(input);sel.removeAllRanges();sel.addRange(range);input.select();}pmNotify(ok?"Chemin copié.":"Sélectionnez puis copiez le chemin.");}
  if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(value).then(function(){pmNotify("Chemin copié.");},fallback);else fallback();
}
function pmDetailHandleClick(e){var b=e.target.closest("[data-detail-action]");if(!b)return;var a=b.dataset.detailAction,pid=b.dataset.pid,kind=b.dataset.kind,p,item,items;
  if(a==="add"||a==="edit"){pmDetailOpen(kind,pid,b.dataset.id||"",b);return;}
  if(a==="close"){pmCloseDialog(b.closest("dialog"));return;}
  if(a==="copy-path"){pmDetailCopy(b.dataset.target||"",b);return;}
  if(a==="delete"){var form=b.closest("form");document.getElementById("pmDetailDeleteText").textContent="Supprimer cet élément ? Cette opération ne peut pas être annulée.";document.getElementById("pmDetailDeleteConfirm").dataset.pid=form.elements.pid.value;document.getElementById("pmDetailDeleteConfirm").dataset.kind=form.elements.collection.value;document.getElementById("pmDetailDeleteConfirm").dataset.id=form.elements.itemId.value;pmOpenDialog("pmDetailDeleteDialog",b);return;}
  if(a==="confirm-delete"){p=PM.get(pid);items=pmDetailItems(p,kind).filter(function(x){return x.id!==b.dataset.id;});try{PM.update(pid,(function(){var o={};o[kind]=items;return o;})());pmCloseDialog(document.getElementById("pmDetailDeleteDialog"));pmCloseDialog(document.getElementById("pmDetailDialog"));pmDetailRender();pmNotify("Élément supprimé.");}catch(ex){document.querySelector("#pmDetailDeleteDialog .pmFormError").textContent=ex.message||"Suppression impossible.";}return;}
}
function pmDetailHandleChange(e){var el=e.target;if(el.dataset.detailAction!=="toggle")return;var p=PM.get(el.dataset.pid),items=pmDetailItems(p,el.dataset.kind).map(function(x){var y=Object.assign({},x);if(x.id===el.dataset.id)y.done=el.checked;return y;});if(!pmDetailUpdate(el.dataset.pid,el.dataset.kind,items,"Mise à jour enregistrée."))el.checked=!el.checked;}
function pmDetailHandleSubmit(e){var form=e.target;if(!form.matches("[data-detail-form]"))return;e.preventDefault();var fd=new FormData(form),err=form.querySelector(".pmFormError");if(err)err.textContent="";try{
  if(form.dataset.detailForm==="decision"){var text=String(fd.get("text")||"").trim();if(!text)throw new Error("Saisissez la décision.");PM.addDecision(String(fd.get("pid")),text);form.reset();pmDetailRender();pmNotify("Décision ajoutée.");return;}
  var pid=String(fd.get("pid")),kind=String(fd.get("collection")),id=String(fd.get("itemId")),p=PM.get(pid),items=pmDetailItems(p,kind).map(function(x){return Object.assign({},x);}),current=items.find(function(x){return x.id===id;}),value={id:id||pmDetailId()};
  if(kind==="milestones"){value.title=String(fd.get("title")||"").trim();value.date=String(fd.get("date")||"");value.done=current?!!current.done:false;if(!value.title)throw new Error("Le titre du jalon est requis.");}
  else if(kind==="readiness"){value.title=String(fd.get("title")||"").trim();value.done=current?!!current.done:false;if(!value.title)throw new Error("Le libellé est requis.");}
  else if(kind==="documents"){value.title=String(fd.get("title")||"").trim();value.kind=String(fd.get("kind")||"url");value.target=String(fd.get("target")||"").trim();if(!value.title||!value.target)throw new Error("Le nom et l’adresse sont requis.");if(value.kind==="url"&&!pmDetailUrl(value.target))throw new Error("Utilisez une adresse commençant par http:// ou https://.");}
  else{value.name=String(fd.get("name")||"").trim();value.role=String(fd.get("role")||"").trim();value.email=String(fd.get("email")||"").trim();value.phone=String(fd.get("phone")||"").trim();if(!value.name)throw new Error("Le nom est requis.");}
  if(current)items[items.indexOf(current)]=value;else items.push(value);PM.update(pid,(function(){var o={};o[kind]=items;return o;})());pmCloseDialog(document.getElementById("pmDetailDialog"));pmDetailRender();pmNotify(current?"Élément modifié.":"Élément ajouté.");
}catch(ex){if(err)err.textContent=ex.message||"Vérifiez les informations saisies.";else pmNotify(ex.message||"Opération impossible.");}}

function initProjectDetailsUI(){
  if(projectDetailsUI.initialized)return;document.body.insertAdjacentHTML("beforeend",'<dialog class="pmDialog" id="pmDetailDialog"><div class="pmDialogHead"><h2 id="pmDetailDialogTitle">Détail</h2><button class="pmClose" data-detail-action="close" aria-label="Fermer">×</button></div><form class="pmForm" id="pmDetailForm" data-detail-form="item"><input type="hidden" name="pid"><input type="hidden" name="collection"><input type="hidden" name="itemId"><div class="pmFields pmDetailDynamicFields"></div><div class="pmFormError" role="alert"></div><div class="pmFormActions"><button type="button" class="pmBtn pmBtnDanger" data-detail-action="delete" hidden>Supprimer</button><span style="flex:1"></span><button type="button" class="pmBtn" data-detail-action="close">Annuler</button><button type="submit" class="pmBtn pmBtnPrimary">Enregistrer</button></div></form></dialog><dialog class="pmDialog pmDetailDeleteDialog" id="pmDetailDeleteDialog"><div class="pmDialogHead"><h2>Confirmer la suppression</h2><button class="pmClose" data-detail-action="close" aria-label="Fermer">×</button></div><div class="pmForm"><p id="pmDetailDeleteText"></p><div class="pmFormError" role="alert"></div><div class="pmFormActions"><button type="button" class="pmBtn" data-detail-action="close">Annuler</button><button type="button" class="pmBtn pmBtnDanger" id="pmDetailDeleteConfirm" data-detail-action="confirm-delete">Supprimer</button></div></div></dialog>');
  document.addEventListener("click",pmDetailHandleClick);document.addEventListener("change",pmDetailHandleChange);document.addEventListener("submit",pmDetailHandleSubmit);document.addEventListener("toggle",function(e){var d=e.target;if(d.matches(".pmDetailSection"))projectDetailsUI.collapsed[d.dataset.pid+":"+d.dataset.detailSection]=!d.open;},true);
  [document.getElementById("pmDetailDialog"),document.getElementById("pmDetailDeleteDialog")].forEach(function(d){d.addEventListener("click",function(e){if(e.target===d)pmCloseDialog(d);});d.addEventListener("cancel",function(e){e.preventDefault();pmCloseDialog(d);});});projectDetailsUI.initialized=true;
}
